language: perl

install:
  - cpanm -n Dist::Zilla
  - cpanm authordeps --missing | cpanm -n
  - cpanm -n Test::CPAN::Changes Test::EOL Test::Fixme Test::NoTabs Test::Pod::Spelling::CommonMistakes Test::Spelling Test::Strict Test::Version Test::Vars || true
  - cpanm Shell::Config::Generate Capture::Tiny Shell::Guess

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

before_script: perlbrew list
script: HARNESS_IS_VERBOSE=1 prove -lv t xt
